### ISSUE TITLE
SQLite3::SQLException

### ISSUE THREAD

**Issue by ZAJDAN** [iridakos/duckrails#67]
```
Puma caught this error: SQLite3::SQLException: no such table: application_state: SELECT  "application_state".* FROM "application_state"  ORDER BY "application_state"."id" DESC LIMIT 1 (ActiveRecord::StatementInvalid)
/var/lib/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/var/lib/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/var/lib/gems/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:284:in `block in exec_query'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/querying.rb:39:in `find_by_sql'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:639:in `exec_queries'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:515:in `load'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation.rb:243:in `to_a'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/finder_methods.rb:127:in `first'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/querying.rb:3:in `first'
/home/watcher/duckrails/app/models/duckrails/application_state.rb:24:in `instance'
/home/watcher/duckrails/lib/duckrails/synchronizer.rb:10:in `call'
/var/lib/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `block in call'
/var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/lib/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/var/lib/gems/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
/var/lib/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.11/lib/rack/lock.rb:17:in `call'
/var/lib/gems/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
/var/lib/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
/var/lib/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.11/lib/rack/content_length.rb:15:in `call'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```
_headless Debian10 x64_

**Comment by ZAJDAN** [comment]
Iam sorry, my mistake. I forgot:
 rake db:migrate 
 bundle exec rake db:setup
