### ISSUE TITLE
Cant run the docker image in Mac with Apple chip

### ISSUE THREAD

**Issue by bindulaxminarayan** [iridakos/duckrails#76]
I am seeing the below error when I tried to run the ducktails docker image in MacBook with apple chip.

docker run -p 9999:80 -v /Users/bindu/dockerimgs/duckrails:/opt/duckrails/db iridakos/duckrails:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
WARNING: Environment variable SECRET_KEY_BASE has not been set - Setting a random SECRET_KEY_BASE
rake aborted!
ActiveRecord::StatementInvalid: Could not find table 'mocks'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:501:in `table_structure'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:375:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/attributes.rb:93:in `columns'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/attributes.rb:98:in `columns_hash'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:48:in `columns_hash'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/calculations.rb:184:in `block in pluck'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/calculations.rb:183:in `map'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/relation/calculations.rb:183:in `pluck'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.1/lib/active_record/querying.rb:14:in `pluck'
/opt/duckrails/lib/duckrails/router.rb:15:in `register_current_mocks'
/opt/duckrails/config/initializers/register_mocks.rb:4:in `<top (required)>'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `each'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `each'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
/opt/duckrails/config/environment.rb:5:in `<top (required)>'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/duckrails/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
Srichakrabindus-MacBook-Pro:duckrails bindu$ ruby
^CTraceback (most recent call last):
ruby: Interrupt

**Comment by jmh** [comment]
I ran into this problem too (the mocks table, not the processor warning) on my intel mac. The issue resolved when I gave a relative path for the `-v` option.
